[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_staking_program = "DwbF8uMsSLVim8f7xj4kU6ND3SH2Z9rYJsiGCCyFDNkb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
